### ISSUE TITLE
Update targetSdkVersion to 26 or greater (from 25) [Android application]

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-android#1]
### Task
Google Play has emailed me to require a high targetSdkVersion for this app. The [current version is 25](https://github.com/intermine/intermine-android/blob/master/app/build.gradle#L10) and it needs to be at least 26, before the start of november

To pick this up: 
1. Comment on this issue to say you're picking it up! 
2. Make the change described above. You can contact me at any point if you have questions! 
3. Make a PR when you think the change is ready and working. 

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by dimivrn** [comment]
Hello, i am picking it up!

**Comment by yochannah** [comment]
Awesome! Ping me of you have any questions!

**Comment by Swapnil9090** [comment]
I would also like to work on this. Can i work for this application?

**Comment by yochannah** [comment]
Oh my gosh, thanks everyone who contributed to this! 

I think I have three PRs for the issue now and I'll have to chose only one, unfortunately - I'll review after the weekend based on who came first.

**Comment by yochannah** [comment]
@Swapnil9090 Thanks so much for volunteering, but I think we have what we need for this issue. 👍
