### ISSUE TITLE
Migrate Android app to pull list of possible sites from registry via http GET

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-android#2]
Currently, this application lists InterMine instances that are hardcoded in this file: https://github.com/intermine/intermine-android/blob/master/app/src/main/res/values/arrays.xml#L3 

We now have a registry at http://registry.intermine.org/ (source + docs: https://github.com/intermine/intermine-registry ) - so it doesn't need to be hardcoded any longer. It would be great if the app could fetch the list of InterMines from the registry instead of them being hardcoded, and store them locally after the first load in case the registry is ever down. 

To pick this up: 
1. Comment on this issue to say you're picking it up! 
2. Make the change described above. You can contact me at any point if you have questions! 
3. Make a PR when you think the change is ready and working. 

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by adikul30** [comment]
Picking up this issue !

**Comment by adikul30** [comment]
Just to be clear, you only need _mines_names_, _mines_service_urls_ and _mines_web_app_urls_ to be fetched and nothing else right ?
Also, I couldn't find _mines_service_urls_ in the GET response.

**Comment by yochannah** [comment]
Hey @adikul30, thanks for picking this up! 🎈 

You're right re the three vars needed. For _mine_service_urls_, just use the url property from http://registry.intermine.org/service/instances and add `/service` to the end - I think that should be safe.

**Comment by ram2012k** [comment]
Picking up the issue

**Comment by yochannah** [comment]
Hey @ram2012k - thanks for volunteering! @adikul30 has already volunteered so let's perhaps give them a chance to do this first. Thanks though! :)

**Comment by adikul30** [comment]
Actually, I don't think I can take time out this week or the next. @ram2012k I wouldn't mind you starting on this 👍 I would definitely look to contribute on other issues once free.

**Comment by yochannah** [comment]
Thanks for letting us know Aditya!

@ram2012k go ahead! :)

**Comment by ram2012k** [comment]
@yochannah Hi , Is there any current use of files in **org.intermine.app.sqlite;** package ?

**Comment by ram2012k** [comment]
please review

**Comment by yochannah** [comment]
This was fixed by #6
